src/AIProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include("Prediction.urls")),
]


if settings.DEBUG:

    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

src/Prediction/urls.py
from django.conf.urls import url
from .views import Home

app_name="Prediction"
urlpatterns = [
    url(r'^$', Home,name="home"),
]

src/Prediction/models.py
from django.db import models


class Company(models.Model):

    company_Name    =models.CharField(max_length=250)
    month           =models.DateField(auto_now=False, auto_now_add=False)
    rising          =models.CharField(max_length=250)
    down            =models.CharField(max_length=250)


    class Meta:
         ordering=["-rising"]

    def __str__(self):

        return self.company_Name

src/Prediction/forms.py
from django import forms


class PredictForm(forms.Form):

    name_of_company     = forms.CharField(label="Enter Company Ticker")

src/Prediction/views.py
import datetime
from django.shortcuts import render
from .models import Company
from .forms import PredictForm
from .predictor import predict_price,get_data,dates_final,prices




def Home(request):

    predicted = 0
    errors=""
    ticker = ""

    qs=Company.objects.all()
    form = PredictForm(request.POST or None)

    if form.is_valid():

        compnay_name = form.cleaned_data['name_of_company']

        if compnay_name.upper() == "AAPL":
            ticker = "Apple Inc."
        if compnay_name.upper() == "GOOG":
            ticker = "Alphabet Inc."


        find_data_set= compnay_name.upper()+".csv"
        
        try:
            data_set = "Data-Set/"+find_data_set
            tday= datetime.datetime.now().day
            get_data(data_set)
            predicted_price, coefficient, constant = predict_price(dates_final,prices,tday)
            predicted ="%.2f" % (predicted_price)
        except:
            errors = "Company Not Found !!!"


    template_name="Prediction/home.html"
    context={
                "qs":qs,
                "form":form,
                "predicted":predicted,
                "errors":errors,
                "ticker":ticker
            }

    return render(request,template_name,context)

src/templates/Prediction/home.html
{% load static %}
{% load crispy_forms_tags %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Stock Market Prediction</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "css/jumbotron.css" %}" rel="stylesheet">
    <link href="{% static "css/style.css" %}" rel="stylesheet">
    <link href="{% static "css/circle.css" %}" rel="stylesheet">
    <link href="{% static "css/dashboard.css" %}" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
  </head>

  <body>

      <header>
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
          <a class="navbar-brand" href="{% url "Prediction:home" %}">Stock Market Prediction</a>
          <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url "Prediction:home" %}">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Profile</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Help</a>
              </li>
            </ul>
            <form class="form-inline mt-2 mt-md-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
          </div>
        </nav>
      </header>

      <div class="container-fluid">
        <div class="row">
          <nav class="col-sm-3 col-md-2 d-none d-sm-block bg-light sidebar">
            <ul class="nav nav-pills flex-column">
              <li class="nav-item">
                <a class="nav-link active" href="#">Overview <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Reports</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Analytics</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Export</a>
              </li>
            </ul>

            <ul class="nav nav-pills flex-column">
              <li class="nav-item">
                <a class="nav-link" href="#">Nav item</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Nav item again</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">One more nav</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Another nav item</a>
              </li>
            </ul>

            <ul class="nav nav-pills flex-column">
              <li class="nav-item">
                <a class="nav-link" href="#">Nav item again</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">One more nav</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Another nav item</a>
              </li>
            </ul>
          </nav>

          <main role="main" class="col-sm-9 ml-sm-auto col-md-10 pt-3">
            <font face = "Times New Roman" size = "10">Predict Todays Stock Prices</font><br>

            <section class="row text-center placeholders">
              <div class="col-md-6">
                  <form action="" method="POST"> {% csrf_token %}
                    <font face = "Times New Roman" size = "5">{{ form|crispy }}</font>
                    <br>
                    <input type="submit" value="Predict Now" class="btn btn-info"/>
                  </form>
              </div>
              <div class="col-sm-6">
                <font face = "Times New Roman" size = "10">Predicted Result</font>
                 <br>
                {% if errors != "" %}
                  <font face = "Times New Roman" size = "5" color="red">{{ errors }}</font>
                {% else %}
                  {% if predicted == 0 %}
                      <font face = "Times New Roman" size = "5" color="red">You do not predict yet.</font>
                  {% else %}
                      <font face = "Times New Roman" size = "5">
                        {{ ticker }}
                      </font>
                      <br>
                      <font face = "Times New Roman" size = "5">Closing Price : </font> <font face = "Times New Roman" size = "7" color="green">$ {{ predicted }}</font>
                  {% endif %}
                {% endif %}
              </div>
            </section>

            <font face = "Times New Roman" size = "10">All Tickers</font>
            <div class="table-responsive">
              <table class="table table-striped">
                <thead>
                  <tr>
                    <th>#</th>
                    <th>Company Name</th>
                    <th>Ticker</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>1</td>
                    <td>Apple Inc.</td>
                    <td>AAPL</td>
                  </tr>
                  <tr>
                    <td>2</td>
                    <td>Alphabet Inc.</td>
                    <td>GOOG</td>
                  </tr>
                </tbody>
              </table>
            </div>
            <footer class="container">
                <p>&copy; SEC 2017</p>
            </footer>
          </main>
        </div>
      </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static "js/jquery-3.2.1.slim.min.js" %}" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="{% static "js/popper.min.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
  </body>
</html>